// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtLHsM-sOXte7BUIW0-zzZXWNKXMx6dPo',
    appId: '1:412999448232:web:6d3681775cbb99e36c749d',
    messagingSenderId: '412999448232',
    projectId: 'mynotes-flutter-app786',
    authDomain: 'mynotes-flutter-app786.firebaseapp.com',
    storageBucket: 'mynotes-flutter-app786.appspot.com',
    measurementId: 'G-3PQ15HX871',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTh2ORtQkt8t9frzV7i0VCdv7s_OfPzU',
    appId: '1:412999448232:android:cedd7f47cbefaf1a6c749d',
    messagingSenderId: '412999448232',
    projectId: 'mynotes-flutter-app786',
    storageBucket: 'mynotes-flutter-app786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxv_u8ZiHvGxTdV_k2seOKzzSDlDvyCo',
    appId: '1:412999448232:ios:556f05526e5398ac6c749d',
    messagingSenderId: '412999448232',
    projectId: 'mynotes-flutter-app786',
    storageBucket: 'mynotes-flutter-app786.appspot.com',
    iosClientId: '412999448232-9fcf9pucadf98fja8m0162r7sjj3clq2.apps.googleusercontent.com',
    iosBundleId: 'com.devanshityagi.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxv_u8ZiHvGxTdV_k2seOKzzSDlDvyCo',
    appId: '1:412999448232:ios:556f05526e5398ac6c749d',
    messagingSenderId: '412999448232',
    projectId: 'mynotes-flutter-app786',
    storageBucket: 'mynotes-flutter-app786.appspot.com',
    iosClientId: '412999448232-9fcf9pucadf98fja8m0162r7sjj3clq2.apps.googleusercontent.com',
    iosBundleId: 'com.devanshityagi.mynotes',
  );
}
